version: 2
updates:
  - package-ecosystem: gradle
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: friday
      time: "12:00"
      timezone: Europe/Amsterdam
    commit-message:
      prefix: "build"
      include: "scope"
    open-pull-requests-limit: 99
